package:
  name: grafana-backup
  version: 0.0.0
  epoch: 0
  description: "A Python-based tool to backup and restore Grafana settings"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python-3.10

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - build-base
      - busybox
      - python-3.10
      - python-3.10-dev
      - py3.10-pip
      - py3.10-poetry-bin

pipeline:
  - runs: |
      cd /home/build
      poetry build
      pip install --ignore-installed --prefix=/usr --root="${{targets.destdir}}" dist/*.whl
      install -Dm755 entrypoint.sh "${{targets.destdir}}/usr/bin/grafana-backup-entrypoint"

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - runs: |
        test -f /usr/bin/grafana-backup
